sudo: required # This command gives the required permissions
services:
  - docker # We need docker to create the containers

before_install:
    # First build the image
  - docker build -t Harsha92/docker-react -f Dockerfile.dev .

script:
    # Run the test suit
  - docker run -e CI=true Harsha92/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-096424354293"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
