sudo: required # This command gives the required permissions
services:
  - docker # We need docker to create the containers

before_install:
    # First build the image
  - docker build -t harsha333/docker-react -f Dockerfile.dev .

script:
    # Run the test suit
  - docker run -e CI=true harsha333/docker-react npm run test -- --coverage

language: generic 
